

name: Node.js Package

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '5 8 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm install
          
  email:
    # The type of runner that the job will run on
    needs: publish-npm
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name:  Send email, you star
        uses: dawidd6/action-send-mail@v1.3.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: 0000dsingh@gmail.com
          password: Deepak@2000
          subject: Report for App
          body: ${{ github.actor }} just starred your mail-on-star repo!!! ${{ github.repository }} - ${{github.repository_owner}}
          to: deepak.1.kumar@apisero.com
          from: 0000dsingh@apisero.com
